# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0004_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='users_visit',
            new_name='user_visit',
        ),
    ]
