# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0005_auto_20181213_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(default='Regular', max_length=255),
        ),
    ]
