# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0006_user_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kids_club_member',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
