# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0008_auto_20181216_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0, max_length=6)),
                ('user_payments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gymadmin.User')),
            ],
        ),
    ]
