# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymadmin', '0010_auto_20181220_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='desc',
            field=models.CharField(default='', max_length=125),
        ),
    ]
